# Generated by Django 4.0.4 on 2022-04-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProduto', models.CharField(max_length=30)),
                ('produto', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('validade', models.DateField(null=True)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
